title: AIML Projects
description: Demo Projects for the AIML Team

show_downloads: true
google_analytics: G-X29GWR9LQS

theme: jekyll-theme-cayman

permalink: pretty

breadcrumbs:
  root:
    hide: false # show breadcrumbs on root/home page
    image: false # Show image or title text
