title: AIML Projects
description: Demo Projects for the AIML Team

show_downloads: true
google_analytics: G-X29GWR9LQS

theme: jekyll-theme-cayman

permalink: pretty

comments: true

related_by: tags categories # Match on both categories and tags
related_limit: 6 # Include 6 related pages
related_categories: 1 # Match at least 1 category
related_tags: 1 # AND at least 1 tag.
